### ISSUE TITLE
stream deallocated  when it is not closed

### ISSUE THREAD

**Issue by qzhuyan** [emqx/quic#127]
caught in a PR:
https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334

test case: 

`tc_stream_send_shutdown_complete`

This is assertion error, but the test was executed without lttng/snk log.
```
Program terminated with signal SIGABRT, Aborted.
[546](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:547)
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
[547](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:548)
[Current thread is 1 (Thread 0x7fab74e0f700 (LWP 1921))]
[548](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:549)
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
[549](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:550)
#1  0x00007fabb8a45859 in __GI_abort () at abort.c:79
[550](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:551)
#2  0x00007fabb8a45729 in __assert_fail_base (
[551](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:552)
    fmt=0x7fabb8bdb588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
[552](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:553)
    assertion=0x7fab4e95a06e "s_ctx->is_closed == TRUE", 
[553](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:554)
    file=0x7fab4e95a020 "/home/runner/work/quic/quic/c_src/quicer_nif.c", 
[554](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:555)
    line=791, function=<optimized out>) at assert.c:92
[555](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:556)
#3  0x00007fabb8a56fd6 in __GI___assert_fail (
[556](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:557)
    assertion=0x7fab4e95a06e "s_ctx->is_closed == TRUE", 
[557](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:558)
    file=0x7fab4e95a020 "/home/runner/work/quic/quic/c_src/quicer_nif.c", 
[558](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:559)
    line=791, 
[559](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:560)
    function=0x7fab4e95b5e0 <__PRETTY_FUNCTION__.23883> "resource_stream_dealloc_callback") at assert.c:101
[560](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:561)
#4  0x00007fab4e74f581 in resource_stream_dealloc_callback (
[561](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:562)
    env=0x7fab74e0a7e0, obj=0x55969b6471e8)
[562](https://github.com/emqx/quic/actions/runs/3248143092/jobs/5329167334#step:5:563)
    at /home/runner/work/quic/quic/c_src/quicer_nif.c:791
```

**Comment by qzhuyan** [comment]
caught 2nd time:
testcase: 
```
[quicer_SUITE:tc_stream_start_flag_shutdown_on_fail/1
```
```
#1  0x00007fb9193d5859 in __GI_abort () at abort.c:79
#2  0x00007fb9193d5729 in __assert_fail_base (
    fmt=0x7fb91956b588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x7fb8cece406e "s_ctx->is_closed == TRUE", 
    file=0x7fb8cece4020 "/home/runner/work/quic/quic/c_src/quicer_nif.c", 
    line=788, function=<optimized out>) at assert.c:92
#3  0x00007fb9193e6fd6 in __GI___assert_fail (
    assertion=0x7fb8cece406e "s_ctx->is_closed == TRUE", 
    file=0x7fb8cece4020 "/home/runner/work/quic/quic/c_src/quicer_nif.c", 
    line=788, 
    function=0x7fb8cece55a0 <__PRETTY_FUNCTION__.22961> "resource_stream_dealloc_callback") at assert.c:101
#4  0x00007fb8ceaa3581 in resource_stream_dealloc_callback (
    env=0x7fb8d5efe7a0, obj=0x7fb8d8b03e48)
    at /home/runner/work/quic/quic/c_src/quicer_nif.c:788
#5  0x000055cb3a48cfa5 in ?? ()
#6  0x000055cb3a2eea36 in ?? ()
#7  0x000055cb3a2f4632 in ?? ()
#8  0x000055cb3a3044ea in erts_schedule ()
#9  0x000055cb3a2dfe3c in process_main ()
#10 0x000055cb3a2edffe in ?? ()
#11 0x000055cb3a566e80 in ?? ()
#12 0x00007fb9195ad609 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
#13 0x00007fb9194d2133 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
