### ISSUE TITLE
assertion failed in CT

### ISSUE THREAD

**Issue by qzhuyan** [emqx/quic#263]
QUIC bug check reports connection are not all closed while unload the NIF module, this only effects `hot upgrade` AND with `DEBUG` build.
```
#4  0x00007f8248e287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f81a832358d in quic_bugcheck (
    File=File@entry=0x7f81a84d2878 "/home/runner/work/quic/quic/msquic/src/core/library.c", Line=Line@entry=521, 
    Expr=Expr@entry=0x7f81a84d2cb0 "MsQuicLib.ConnectionCount == 0")
    at /home/runner/work/quic/quic/msquic/src/platform/platform_posix.c:93
#6  0x00007f81a82d2c3e in MsQuicLibraryUninitialize ()
    at /home/runner/work/quic/quic/msquic/src/core/library.c:521
#7  0x00007f81a82d2f3a in MsQuicRelease ()
    at /home/runner/work/quic/quic/msquic/src/core/library.c:638
#8  0x00007f81a82d398f in MsQuicClose (QuicApi=<optimized out>)
    at /home/runner/work/quic/quic/msquic/src/core/library.c:1721
#9  0x00007f81a82bd7f5 in closeLib (env=0x7f8204f96870, argc=0, argv=0x0)
    at /home/runner/work/quic/quic/c_src/quicer_nif.c:1221
#10 0x00007f81a82bd3c4 in on_unload (env=0x7f8204f96870, priv_data=0x0)
    at /home/runner/work/quic/quic/c_src/quicer_nif.c:1147
#11 0x000055ea8e4fffec in close_dynlib (lib=0x55ea8f75e038)
    at beam/erl_nif.c:2279
#12 0x000055ea8e50a118 in erts_unload_nif (lib=0x55ea8f75e038)
    at beam/erl_nif.c:5021
#13 0x000055ea8e37ee01 in erts_internal_purge_module_2 (A__p=0x55ea8f7904d0, 
    BIF__ARGS=<optimized out>, A__I=<optimized out>)
    at beam/beam_bif_load.c:2035
```

**Comment by qzhuyan** [comment]
haven't seen this for long time, assume it is solved.
